# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_auto_20170823_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytic',
            name='clicks',
        ),
        migrations.AddField(
            model_name='url',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
